---
  - name: check if podman is installed
    shell: "dnf list installed podman"
    become: yes
    register: podman_installed
    tags: test
  
  - name: debug
    debug:
      var: podman_installed.stdout
    tags: test

  - name: Disable container-tools module
    shell: "dnf -y module disable container-tools"
    args:
      executable: /bin/bash
      warn: false
    become: yes

  - name: Install dnf copr plugin
    shell: "dnf install -y 'dnf-command(copr)'"
    args:
      executable: /bin/bash
    become: yes

  - name: Install container-selinux 
    shell: "dnf -y copr enable rhcontainerbot/container-selinux"
    args:
      executable: /bin/bash
    become: yes

  - name: Install podman repo
    get_url:
      url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/devel:kubic:libcontainers:stable.repo"
      dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo
    become: yes

  - name: Install podman
    dnf:
      name: podman
      state: latest
    become: yes
  